-- alter the warehouse

ALTER WAREHOUSE FIRST_WH RESUME 

ALTER WAREHOUSE FIRST_WH SUSPEND



-- to change the property use keyword 'SET'

ALTER WAREHOUSE FIRST_WH SET WAREHOUSE_SIZE = 'XSMALL'
ALTER WAREHOUSE FIRST_WH SET WAREHOUSE_SIZE = SMALL

ALTER WAREHOUSE FIRST_WH SET AUTO_SUSPEND = 60




-- delete warehouse

DROP WAREHOUSE FIRST_WH
